HW13 : Added HTTP API, Refactoring
FRiniZ/otus-go-hw-test pull request #14
Opened 2023-01-17 13:46 UTC by FRiniZ

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-18 11:38 UTC, dshemin requested changes

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc ListEventsV1 (RequestV1) returns (ReplyV1){};
Важно:

А зачем нам при получении списка событий, передавать событие?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc LookupEventV1 (RequestV1) returns (ReplyV1){};
Важно:

Мы ищем событие, делаем это по какому полю из переданного события? Что будет если событие не передали?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc InsertEventV1 (RequestV1) returns (ReplyV1) {};
Важно:

Мы создали одно событие почему в ответе сказано что может вернуться несколько событий?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc UpdateEventV1 (RequestV1) returns (ReplyV1){};
Важно:

Мы обновили одно событие почему в ответе сказано что может вернуться несколько событий?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc DeleteEventV1 (RequestV1) returns (ReplyV1){};
Важно:

Мы удаляем событие по какому полю из переданного события? И какие события мы должны вернуть после удаления?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +syntax = "proto3";
Важно:

Вижу что возникли трудности с дизайном gRPC АПИ. RPC - remote procedure call - удаленный вызов процедур, т.е. вы как бы описываете функции которые можно вызвать удалённо. И описывать их дизайн надо соответствующе, так же как и функцию в коде. Естественно можно написать так:

```
func ReverString(v interface{}) *interface{}
```

но так лучше:
```
func ReverseString(s string) string
```

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	go generate ./cmd/calendar/main.go
Совет:

Лучше `go generate ./...`, более универсально

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +service Calendar {
Критично:

А где реализация обязательных методов из ТЗ:

СписокСобытийНаДень (дата);
СписокСобытийНаНеделю (дата начала недели);
СписокСобытийНaМесяц (дата начала месяца).

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		ctx, cancel := context.WithTimeout(ctx, time.Second*3)
Важно:

Тут должен использоваться новый контекст, потому как к этому моменту базовый контекст уже может быть закрыт!

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	g, _ := errgroup.WithContext(ctx)
Важно:

Надо использовать тот контекст, который вернул метод

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) CheckBasicRules(e *storage.Event, checkID bool) error {
Важно:

Этот метод разве должен быть пулбличным?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		return fmt.Errorf("%w(empty OffTime)", ErrOffTime)
Важно:

В голанге принято объединять ошибки с помощью  ':', например: "%w: empty". Сейчас же мы получим: "wrong OffTime(empty OffTime)". Не канонично и слишком много упоминаний об OffTime в такой короткой строке.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		fmt.Printf("\n\nNotifyTime:%v\n\n", e.NotifyTime)
Важно:

Остатки отладки? Если нужно, то использовать логер.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) EmptyDate(ctx context.Context, userID int64, date time.Time) (bool, error) {
Важно:

Метод точно должен быть публичным?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	return a.storage.UpdateEvent(ctx, event)
Важно:

При обновлении мы можем поменять дату, и так, как проверки на занятость даты нет, нарушить наш инвариант, получить более одного события в одно и тоже время.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if err := a.CheckBasicRules(event, true); err != nil {
Важно:

А зачем валидировать всё событие, если нам нужно только id? Зачем нам тут вообще всё событие? Получается, чтобы удалить мне сначала его надо достать из БД, а потом уже удалять. В итоге мы имеем два запроса вместо одного.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) ListEvents(ctx context.Context, userID int64) ([]storage.Event, error) {
Критично:

Нет реализации методов из ТЗ:

СписокСобытийНаДень (дата);
СписокСобытийНаНеделю (дата начала недели);
СписокСобытийНaМесяц (дата начала месяца).

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app_test.go
> +func TestApp(t *testing.T) {
Важно:

Лучше писать тестовый метод для каждой отдельной функции.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +func (s *Service) Log(ctx context.Context) {
Важно:

У вас есть middleware для инъекции логера, можно в ней же и залогировать, чтобы не писать в каждом методе.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	_ = event // to avoid lint err: event declared but not used (typecheck)
Важно:

Кажется это более не актуально.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	return grpc.ErrServerStopped
Важно:

А зачем тут возвращать ошибку? У нас же всё нормально.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  	w.Write([]byte("hello-world"))
Важно:

Это уже нам не нужно и можно удалить.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
Важно:

Эти таймауты логичнее вынести в сервис.

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +			s.log.Errorf("LookupEvent:%v\n", err)
Важно:

ListEvent

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +func (s *Server) Shutdown(w http.ResponseWriter, r *http.Request) {
Важно:

Можете объяснить, зачем тут этот метод?

2023-01-18 11:38 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `SELECT id
Критично:

Не обработан случаи пересечения событий, пример:

Дано:

Событие с 11:00 до 12:00

Мы пытаемся добавить событие:
1. 11:30 до 12:30
2. 10:30 до 11:30
3. 11:15 до 11:45

2023-01-18 14:34 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `SELECT id
Fixed

2023-01-18 14:39 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +func (s *Server) Shutdown(w http.ResponseWriter, r *http.Request) {
Выше комментарий был. Наверно сейчас уже не нужен -  удаляю

2023-01-18 14:49 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +			s.log.Errorf("LookupEvent:%v\n", err)
Fixed

2023-01-18 15:10 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
Я не понял на какой уровень нужно вынести?

2023-01-18 15:11 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  	w.Write([]byte("hello-world"))
Fixed

2023-01-18 15:13 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
На уровень Storage?

2023-01-18 15:15 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	return grpc.ErrServerStopped
Осталось после изучения как работать с errgroup.
Поправил

2023-01-18 15:17 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	_ = event // to avoid lint err: event declared but not used (typecheck)
К сожалению не проходит линтер на github. https://files.slack.com/files-pri/THJULHM7E-F04L1GP88TA/image.png в группе обсуждал. Пока только с таким решением проходит

2023-01-18 15:23 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +func (s *Service) Log(ctx context.Context) {
Пытался не получилось. Дело в том что логгер не глобальный. И в инъекции я не могу получить к нему доступ. Правда есть решение передать его туда через metadata. Но мне кажется это не красивым решением. Если одобряете поправлю.

2023-01-18 18:33 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) ListEvents(ctx context.Context, userID int64) ([]storage.Event, error) {
Added

2023-01-18 18:34 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if err := a.CheckBasicRules(event, true); err != nil {
Убрал

2023-01-18 18:36 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +	return a.storage.UpdateEvent(ctx, event)
Там какая была ситуация. Я пытался обновить запись которая существовала но поменял не даты а описание.
И мне не давало добавить проверка. Сейчас поправлю эту проверку чтоб исключала event.ID при проверке если он есть

2023-01-18 18:50 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +	return a.storage.UpdateEvent(ctx, event)
Поправил

2023-01-18 18:53 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) EmptyDate(ctx context.Context, userID int64, date time.Time) (bool, error) {
Поправил

2023-01-18 18:53 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) EmptyDate(ctx context.Context, userID int64, date time.Time) (bool, error) {
Переименовал в isBusyDateTimeRange

2023-01-18 18:53 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +		fmt.Printf("\n\nNotifyTime:%v\n\n", e.NotifyTime)
Да спасибо. Убрал

2023-01-18 18:58 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +		return fmt.Errorf("%w(empty OffTime)", ErrOffTime)
Спасибо за науку. Поправил!

2023-01-18 18:58 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) CheckBasicRules(e *storage.Event, checkID bool) error {
Поправил на checkBasicRules

2023-01-18 19:00 UTC, FRiniZ commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	g, _ := errgroup.WithContext(ctx)
Поправил

2023-01-18 19:01 UTC, FRiniZ commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		ctx, cancel := context.WithTimeout(ctx, time.Second*3)
Спасибо! Поправил

2023-01-19 00:34 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc ListEventsV1 (RequestV1) returns (ReplyV1){};
Переписал.

2023-01-19 00:36 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc InsertEventV1 (RequestV1) returns (ReplyV1) {};
Поправил

2023-01-19 00:36 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc UpdateEventV1 (RequestV1) returns (ReplyV1){};
Поправил

2023-01-19 00:36 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc DeleteEventV1 (RequestV1) returns (ReplyV1){};
Поправил

2023-01-19 00:36 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +syntax = "proto3";
Не знаю насколько правильно сейчас получилось..

2023-01-19 00:36 UTC, FRiniZ commented on hw12_13_14_15_calendar/Makefile
> +	go generate ./cmd/calendar/main.go
Поправил

2023-01-19 00:37 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +service Calendar {
Добавил

2023-01-19 00:38 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	_ = event // to avoid lint err: event declared but not used (typecheck)
```
golangci-lint run ./...
Error: internal/server/grpcservice/service.go:[11](https://github.com/FRiniZ/otus-go-hw-test/actions/runs/3954179945/jobs/6771248271#step:4:12)8:2: event declared but not used (typecheck)
	event, err := s.app.LookupEvent(ctx, *req.ID)
	^
make: *** [Makefile:35: lint] Error 1
Error: Process completed with exit code 2.
```

2023-01-19 13:41 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	_ = event // to avoid lint err: event declared but not used (typecheck)
Тогда лучше `nolint://typecheck` чем так

2023-01-19 13:41 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +func (s *Service) Log(ctx context.Context) {
Мож напичать функцию, которая создаёт мидлварь, т.е. функцию которая создаёт функцию, и замкнуть логер там.

2023-01-19 13:41 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
На уровень сервиса, там где у нас вся логика.

2023-01-19 13:57 UTC, dshemin approved these changes

2023-01-19 13:57 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +message RepEmpty {
Важно:

Уже есть такой тип https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty

2023-01-19 13:57 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if busy, err := a.isBusyDateTimeRange(ctx, event.ID, event.UserID, event.OnTime, event.OffTime); err != nil {
Важно:

Для упрощения советую проверку на busy перенести в isBusyDateTimeRange, сделать так чтобы этот метод возвращал только ошибку.

2023-01-19 13:57 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	w.Write([]byte("[\n"))
Важно:

Погодите, что вы тут делаете? Почему нельзя просто закодировать слайс и отправить?!

2023-01-19 13:57 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) firstDayOfWeek(t time.Time) time.Time {
Важно:

В точности такие же методы я видел и в memory сторадже. Если вы копируете код из одного файла в другой, стоит остановится и задуматься. Копирование - плохо. Вам придётся поддерживать этот код в двух, а если ещё стораджи добавятся, то и в более чем двух местах! У нас же есть сервис, сделайте это там.

2023-01-19 16:10 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +	_ = event // to avoid lint err: event declared but not used (typecheck)
Поправил

2023-01-19 16:10 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/grpcservice/service.go
> +func (s *Service) Log(ctx context.Context) {
Да так получилось

2023-01-19 16:13 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
Хех а там уже есть.. Получается я два раза это делал. Поправил

2023-01-19 16:42 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) firstDayOfWeek(t time.Time) time.Time {
Поправил.

2023-01-19 16:59 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	w.Write([]byte("[\n"))
Спасибо! Поправил.

2023-01-19 17:05 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if busy, err := a.isBusyDateTimeRange(ctx, event.ID, event.UserID, event.OnTime, event.OffTime); err != nil {
Поправил

2023-01-19 17:05 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventService.proto
> +message RepEmpty {
Заменил

2023-01-19 17:05 UTC, FRiniZ commented on hw12_13_14_15_calendar/internal/app/app_test.go
> +func TestApp(t *testing.T) {
Поправил

2023-01-19 17:07 UTC, FRiniZ commented on hw12_13_14_15_calendar/api/EventServiceInterface.proto
> +    rpc LookupEventV1 (RequestV1) returns (ReplyV1){};
Сейчас переписал эти методы. Но проверки на заполнение пока нет.. Надо будет подумать

2023-01-22 09:53 UTC, merged